[package]
name = "denali"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
flate2 = { version = "1.1.5", features = ["zlib"] }
hex = "0.4.3"
sha1 = "0.10.6"

